### ISSUE TITLE
Is there a ppt about this solution?

### ISSUE THREAD

**Issue by jinweiluo** [loserChen/WSDM_CUP_Rec_2022#1]
Hi
Thank you so much for open-sourcing such a good work, I would like to ask if there is any ppt or documentation about this work.

**Comment by loserChen** [comment]
You can see this website https://www.wsdm-conference.org/2022/wp-content/uploads/2022/02/Task3_WSDMCoggle_2nd.pdf

**Comment by jinweiluo** [comment]
Thanks
